config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'

  root to: 'borns#index'

  resources :borns, only: [:show, :new, :create, :index] do
    resources :bets, only: [:new, :create, :edit, :update]
  end

  get '/:name', to: 'borns#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :born
end

app/models/born.rb
class Born < ApplicationRecord
  has_many :bets

  validates :name, presence: true
  validates :birthday, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_born
  http_basic_authenticate_with name: ENV['AUTHENTICATION_NAME'], password: ENV['AUTHENTICATION_PASSWORD'], only: [:edit, :update]

  def new
    @bet = @born.bets.build(when: params[:when])
  end

  def create
    @bet = @born.bets.build(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to "/#{@born.name}", notice: 'Tu apuesta fue registrada!' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @bet = Bet.find(params[:id])
  end

  def update
    @bet = Bet.find(params[:id])

    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to root_path, notice: 'Tu apuesta fue actualizada!' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def bet_params
    params.require(:bet).permit(:name, :when)
  end

  def set_born
    @born ||= Born.find(params[:born_id])
  end
end

app/controllers/borns_controller.rb
class BornsController < ApplicationController
  before_action :set_born, only: [:show]
  before_action :set_date, only: [:show]

  def index
    @borns = Born.all
  end

  def new
    @born = Born.new
  end

  def create
    @born = Born.new(permited_params)

    if @born.save
      redirect_to "/#{@born.name}", notice: "Esperando a #{@born.name}, a compartir!!!"
    else
      render :new
    end
  end

  def show
  end

  private

  def set_born
    @born ||= params[:name].present? ? Born.find_by(name: params[:name]) : Born.find(params[:id])
  end

  def set_date
    params[:start_date] ||= @born.birthday || Date.today
  end

  def permited_params
    params.require(:born).permit(:name, :birthday, :description)
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :set_date

  def index
    @bets = Bet.all
  end

  private

  def set_date
    params[:start_date] ||= ENV['START_DATE'] || Date.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/views/bets/_form.html.erb
<%= form_for([@born, bet]) do |f| %>
  <div class="form-group">
    <% if bet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

        <ul>
          <% bet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :born_id %>

    <div class="form-group">
      <%= f.label :name, 'Tu Nombre' %>
      <%= f.text_field :name, maxlength: 10, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :when, 'En que fecha te parece?' %>
      <%= f.date_select :when, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit('Enviar') %>
    </div>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Actualizá tu apuesta</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Volver', root_path %>

app/views/bets/new.html.erb
<h1>Cuando te parece que llega?</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Volver', root_path %>

app/views/borns/_form.html.erb
<%= form_for @born do |f| %>
  <div class="form-group">
    <% if born.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(born.errors.count, "error") %> prohibited this bet from being saved:</h2>

        <ul>
          <% born.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, 'El nombre del bebe' %>
      <%= f.text_field :name, maxlength: 10, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :birthday, 'Pronostico de posible fecha' %>
      <%= f.date_select :birthday , class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, 'Premios para el ganador' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit('Crear') %>
    </div>
  </div>
<% end %>

app/views/borns/index.html.erb
<h1>Esperando a tus hijos </h1>

<hr>

<section>
  <h2>Nacimientos anteriores</h2>
  <%- @borns.each do |born| %>
    <ul>
      <li>
        <span class="label label-info">
          <%= link_to born.name, born_path(born) %>
        </span>
      </li>
    </ul>
  <% end %>
</section>


<hr>

<h2>Crea el tuyo</h2>
<%= link_to 'nuevo nacimiento', new_born_path %>

app/views/borns/new.html.erb
<h1>Elegí una fecha</h1>

<%= render 'form', born: @born %>

<%= link_to 'Volver', root_path %>

app/views/borns/show.html.erb
<h1>Esperando a <%= @born.name %></h1>

<%= month_calendar(attribute: :when, events: @born.bets) do |date, events| %>
  <%= date.day %>
  <ul>
    <% events.each do |event| %>
      <li>
        <span class="label label-info">
          <%= event.name %>
        </span>
      </li>
    <% end %>
  </ul>
  <%= link_to new_born_bet_path(@born, when: date) do %>
    <button type="button" class="btn">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
  <% end %>
<% end %>

<div id="disqus_thread"></div>
<script>

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://prode-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/calendar/index.html.erb
<h1>Esperando a <%= ENV['NAME'] %></h1>

<%= month_calendar(attribute: :when, events: @bets) do |date, events| %>
  <%= date.day %>
  <ul>
    <% events.each do |event| %>
      <li>
        <span class="label label-info">
          <%= event.name %>
        </span>
      </li>
    <% end %>
  </ul>
  <%= link_to new_born_path(when: date) do %>
    <button type="button" class="btn">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
  <% end %>
<% end %>

<div id="disqus_thread"></div>
<script>

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://prode-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>